module.exports = function(sequelize,DataTypes){
    return sequelize.define(
        'user1',
        {
            id:{
                type:DataTypes.INTEGER,
                primaryKey:true,
                autoIncrement:true
            },
            username:{
                type:DataTypes.STRING,
                field:'username'
            },
            password:{
                type:DataTypes.STRING,
                field:'password'
            },
            phone:{
                type:DataTypes.STRING,
                field:'phone'
            },
            salt:{
                type:DataTypes.STRING,
                field:'salt'
            },
            roleid:{
                type:DataTypes.INTEGER,
                field:'roleid'
            }
        }
    )
}